<?php

declare(strict_types=1);
require __DIR__ . '/db.php';
require __DIR__ . '/layout.php';

$database = db();
$movements = $database->query("SELECT m.*, p.name AS product_name, p.sku, w.name AS warehouse_name FROM inventory_movements m JOIN products p ON p.id = m.product_id JOIN warehouses w ON w.id = m.warehouse_id ORDER BY m.movement_date DESC")->fetchAll();
pageStart('Movements', 'movements');
?><div class="d-flex flex-column flex-md-row justify-content-between align-items-md-end gap-3 mb-4"><div><p class="eyebrow mb-2">Audit trail</p><h1 class="display-6 fw-semibold mb-2">Stock movements</h1><p class="text-secondary mb-0">A complete, filterable history of inventory activity.</p></div><a class="btn btn-dark" href="movement-add.php">+ Record movement</a></div><?php if (isset($_GET['created'])): ?><div class="alert alert-success border-0">Movement recorded and stock balance updated.</div><?php endif; ?><div class="panel"><div class="d-flex flex-column flex-md-row justify-content-between gap-3 mb-3"><h2 class="h5 mb-0">Movement ledger</h2><div class="d-flex gap-2"><input id="movement-search" class="form-control form-control-sm" placeholder="Search movement..." aria-label="Search movements"><select id="movement-filter" class="form-select form-select-sm filter-select" aria-label="Filter movement type"><option value="ALL">All types</option><option value="IN">Inbound</option><option value="OUT">Outbound</option><option value="TRANSFER">Transfers</option><option value="ADJUSTMENT">Adjustments</option></select></div></div><div class="table-responsive"><table class="table align-middle" id="movement-table"><thead><tr><th>Number</th><th>Product</th><th>Warehouse</th><th>Type</th><th>Reference</th><th>Date</th><th class="text-end">Quantity</th><th class="text-end">Stock after</th></tr></thead><tbody><?php foreach ($movements as $movement): ?><tr data-type="<?= e($movement['movement_type']) ?>"><td><strong><?= e($movement['movement_number']) ?></strong></td><td><?= e($movement['product_name']) ?><small class="d-block text-secondary"><?= e($movement['sku']) ?></small></td><td><?= e($movement['warehouse_name']) ?></td><td><?= e($movement['movement_type']) ?></td><td><?= e($movement['reference']) ?></td><td><?= e(date('d M Y H:i', strtotime($movement['movement_date']))) ?></td><td class="text-end"><?= e($movement['quantity']) ?></td><td class="text-end fw-semibold"><?= e($movement['stock_after']) ?></td></tr><?php endforeach; ?></tbody></table></div></div><?php pageEnd(); ?>
